version: '3.8'

services:
  db:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - befake-network

  api-gateway:
    image: api-gateway:latest
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      - befake-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: naming-server:latest
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - befake-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - befake-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always #Restart if there is a problem starting up

  rabbitmq:
    image: rabbitmq:3.8.34-management
    mem_reservation: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - befake-network

  user-service:
    image: user-service:latest
    restart: always
    ports:
      - "8000:8000"
    networks:
      - befake-network
    depends_on:
      - db
      - naming-server
      - api-gateway
      - friend-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/user-service

  post-service:
    image: post-service:latest
    restart: always
    ports:
      - "8001:8001"
    networks:
      - befake-network
    depends_on:
      - db
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/post-service

  friend-service:
    image: friend-service:latest
    restart: always
    ports:
      - "8003:8003"
    networks:
      - befake-network
    depends_on:
      - db
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/friend-service

  interaction-service:
    image: interaction-service:latest
    restart: always
    ports:
      - "8002:8002"
    networks:
      - befake-network
    depends_on:
      - db
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/interaction-service

  auth-service:
    image: authorization-service:latest
    #restart: always
    ports:
      - "8080:8080"
    networks:
      - befake-network
    depends_on:
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411

networks:
  befake-network: