apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/befake-network: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: RABBIT_URI
              value: amqp://guest@rabbitmq:5672
            - name: SPRING.ZIPKIN.BASEURL
              value: http://zipkin-server:9411
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_ZIPKIN_SENDER_TYPE
              value: rabbit
          image: pintertamas/api-gateway:SNAPSHOT-0.0.1
          name: api-gateway
          ports:
            - containerPort: 8765
          resources: {}
      restartPolicy: Always
status: {}
