kind: Deployment
apiVersion: apps/v1
metadata:
  name: friend-service
  namespace: default
  uid: 9ff866b8-f93b-4315-9be4-d44710992beb
  resourceVersion: '174635'
  generation: 10
  creationTimestamp: '2022-12-03T18:13:17Z'
  labels:
    app: friend-service
  annotations:
    deployment.kubernetes.io/revision: '10'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-03T18:13:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"friend-service"}:
                  .: {}
                  f:image: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-04T03:29:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
            f:spec:
              f:containers:
                k:{"name":"friend-service"}:
                  f:env:
                    .: {}
                    k:{"name":"DB_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"DISCOVERY_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"EUREKA_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KAFKA_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KAFKA_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PG_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PG_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SPRING_ZIPKIN_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-04T03:29:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: friend-service
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-12-04T03:29:24Z'
    spec:
      containers:
        - name: friend-service
          image: pintertamas/friend-service:SNAPSHOT-0.0.1
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: 'false'
            - name: SPRING_ZIPKIN_ENABLED
              value: 'false'
            - name: PG_NAME
              value: postgres-friend
            - name: PG_PORT
              value: '5432'
            - name: DB_NAME
              value: postgres
            - name: KAFKA_URL
              value: kafka-service
            - name: KAFKA_PORT
              value: '9092'
            - name: DISCOVERY_CLIENT_ENABLED
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-03T18:24:17Z'
      lastTransitionTime: '2022-12-03T18:24:17Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-12-04T03:29:27Z'
      lastTransitionTime: '2022-12-03T18:13:17Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "friend-service-98894dd46" has successfully progressed.
