kind: Deployment
apiVersion: apps/v1
metadata:
  name: notification-service
  namespace: default
  uid: 43074751-d181-4a33-a8d7-727c1bb13708
  resourceVersion: '174746'
  generation: 16
  creationTimestamp: '2022-12-03T18:13:54Z'
  labels:
    app: notification-service
  annotations:
    deployment.kubernetes.io/revision: '16'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-03T18:13:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"notification-service"}:
                  .: {}
                  f:image: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-04T03:29:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
            f:spec:
              f:containers:
                k:{"name":"notification-service"}:
                  f:env:
                    .: {}
                    k:{"name":"DISCOVERY_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"EUREKA_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KAFKA_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SPRING_ZIPKIN_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-04T03:29:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification-service
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-12-04T03:29:32Z'
    spec:
      containers:
        - name: notification-service
          image: pintertamas/notification-service:kubernetes
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: 'false'
            - name: SPRING_ZIPKIN_ENABLED
              value: 'false'
            - name: KAFKA_URL
              value: kafka-service:9092
            - name: DISCOVERY_CLIENT_ENABLED
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 16
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-03T19:40:55Z'
      lastTransitionTime: '2022-12-03T19:40:55Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-12-04T03:29:44Z'
      lastTransitionTime: '2022-12-03T18:13:54Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "notification-service-684486bb9f" has successfully
        progressed.
