kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-service
  namespace: default
  uid: 93c2a79c-9782-4cfa-b1d5-aad069b10da8
  resourceVersion: '791802'
  generation: 133
  creationTimestamp: '2022-12-02T15:02:08Z'
  labels:
    app: user-service
  annotations:
    deployment.kubernetes.io/revision: '84'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:replicas: {}
      subresource: scale
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-02T15:02:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"user-service"}:
                  .: {}
                  f:image: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-07T16:07:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
            f:spec:
              f:containers:
                k:{"name":"user-service"}:
                  f:env:
                    .: {}
                    k:{"name":"DB_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"DISCOVERY_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"EUREKA_CLIENT_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KAFKA_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KAFKA_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PG_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PG_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SPRING_ZIPKIN_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-07T16:17:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:unavailableReplicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 10
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-12-07T16:07:09Z'
    spec:
      containers:
        - name: user-service
          image: pintertamas/user-service:SNAPSHOT-0.0.1
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: 'false'
            - name: SPRING_ZIPKIN_ENABLED
              value: 'false'
            - name: PG_NAME
              value: postgres-user
            - name: PG_PORT
              value: '5432'
            - name: DB_NAME
              value: postgres
            - name: KAFKA_URL
              value: kafka-service:9092
            - name: KAFKA_PORT
              value: '9092'
            - name: DISCOVERY_CLIENT_ENABLED
              value: 'true'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 133
  replicas: 13
  updatedReplicas: 5
  readyReplicas: 8
  availableReplicas: 8
  unavailableReplicas: 5
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-07T13:53:36Z'
      lastTransitionTime: '2022-12-07T13:53:36Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2022-12-07T16:17:10Z'
      lastTransitionTime: '2022-12-07T16:17:10Z'
      reason: ProgressDeadlineExceeded
      message: ReplicaSet "user-service-86bcd9469" has timed out progressing.
