kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-post
  uid: cd2478b5-514f-4890-b92b-0ac24f879b13
  resourceVersion: '122625'
  creationTimestamp: '2022-12-03T16:29:05Z'
  labels:
    app: postgres-post
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2022-12-03T16:29:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:type: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:hostPath:
            .: {}
            f:path: {}
            f:type: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-03T16:46:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bound-by-controller: {}
        f:spec:
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-03T16:46:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      subresource: status
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data-post
    type: ''
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: postgres-pv-claim-interaction
    uid: 3049382e-3170-402d-84ac-df907e626931
    apiVersion: v1
    resourceVersion: '122623'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
