kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume2
  uid: 97fbf80d-54cc-4a46-87bd-f3a37eab7f2c
  resourceVersion: '12715'
  creationTimestamp: '2022-12-02T16:41:20Z'
  labels:
    app: postgres
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2022-12-02T16:41:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:type: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:hostPath:
            .: {}
            f:path: {}
            f:type: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-02T16:44:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bound-by-controller: {}
        f:spec:
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-02T16:44:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      subresource: status
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data2
    type: ''
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: postgres-pv-claim2
    uid: 98f8a7b9-08b5-41bf-837f-ac32550bfe24
    apiVersion: v1
    resourceVersion: '12711'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
