kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-user
  uid: a3317c4c-faca-46be-8564-8ac87a3257f4
  resourceVersion: '28045'
  creationTimestamp: '2022-12-02T20:05:54Z'
  labels:
    app: postgres-user
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2022-12-02T20:05:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:type: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:hostPath:
            .: {}
            f:path: {}
            f:type: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-02T20:06:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bound-by-controller: {}
        f:spec:
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-02T20:06:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      subresource: status
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data-user
    type: ''
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: postgres-pv-claim-user
    uid: 45aff698-1656-453c-a01c-7709b44211c0
    apiVersion: v1
    resourceVersion: '28041'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
