#
# Build stage
#
FROM maven:3.6.3-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml package clean install

#
# Package stage
#
FROM openjdk:17-alpine
MAINTAINER pintertamas
COPY target/naming-server-kubernetes.jar naming-server-kubernetes.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/naming-server-kubernetes.jar"]
