FROM openjdk:17-alpine
MAINTAINER pintertamas
COPY target/authorization-service-0.0.1-SNAPSHOT.jar authorization-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/authorization-service-0.0.1-SNAPSHOT.jar"]