FROM openjdk:17-alpine
MAINTAINER pintertamas
COPY target/interaction-service-0.0.1-SNAPSHOT.jar interaction-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/interaction-service-0.0.1-SNAPSHOT.jar"]